name: usar matlab
'on':
  push:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          products: Statistics_and_Machine_Learning_Toolbox Signal_Processing_Toolbox
                    Curve_Fitting_Toolbox DSP_System_Toolbox
          
      - name: command
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('simu');
            diary('simu/my_results.txt');
            lab2; 
            diary off;
            exportgraphics(gcf, 'simu/grafica.png', 'Resolution', 300);
            
      - name: Subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: simu

          

     
          
