name: usar matlab
'on':
  push:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          products: Statistics_and_Machine_Learning_Toolbox Signal_Processing_Toolbox
                    Curve_Fitting_Toolbox DSP_System_Toolbox
          
      - name: command
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('lab2_3')
            lab2_3;

      - name: obtener
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)

      - name: Crear carpeta con el nombre del commit
        run: |
         COMMIT_MESSAGE="${{ steps.obtener.outputs.commit_message }}"
         mkdir "$COMMIT_MESSAGE"
         cp lab2_3/* "$COMMIT_MESSAGE/"


      # Commit y push de la carpeta
      - name: Commit y push de la carpeta
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizar artefactos"
          branch: main

          

     
          
