name: usar matlab

on: 
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     
    steps:
  
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
