name: usar matlab

on: 
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     
    steps:
  
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
         relase: 2023b 
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-command@v2
      - name: subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
