name: Usar MATLAB
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          products: Statistics_and_Machine_Learning_Toolbox 
                    Signal_Processing_Toolbox 
                    Curve_Fitting_Toolbox 
                    DSP_System_Toolbox
          
      - name: Ejecutar comando MATLAB
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('simu')


      - name: Subir archivos como artefactos
        uses: actions/upload-artifact@v2
        with:
         name: resultados

