name: usar matlab

on: 
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     
    steps:
  
      - name: revisar repositorio
        uses: actions/checkout@v4

      - name: setup matlab
        uses: matlab-actions/setup-matlab@v2

      - name: matlab test
        run: matlab./lab2.m

      - name: subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
