name: usar matlab

on: 
  push:
    branches: [main]

jobs: 
  builds:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     
    steps:
  
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run all tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: simu
      - name: subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
