name: usar matlab
'on':
  push:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          products: Statistics_and_Machine_Learning_Toolbox Signal_Processing_Toolbox
                    Curve_Fitting_Toolbox DSP_System_Toolbox
          
      - name: command
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('lab2_3')
            lab2_3;

      - name: Crear carpeta de artefactos
        run: |
          mkdir artefactos
          cp lab2_3/* artefactos/
          
      - name: Commit y push de artefactos
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizar artefactos"
          branch: artefactos
          files: artefactos/*

          

     
          
