name: Generar y guardar gráfico en MATLAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          products: Statistics_and_Machine_Learning_Toolbox
          
      - name: Ejecutar script de MATLAB
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('simu')
            lab2
            exportgraphics(fig1, 'simu/grafica1.png', 'Resolution', 100);
            exportgraphics(fig2, 'simu/grafica2.png', 'Resolution', 100);
            exportgraphics(fig3, 'simu/grafica3.png', 'Resolution', 100);

      - name: Subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
         repository: simu

