name: Generar y guardar gráfico en MATLAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          
      - name: Ejecutar script de MATLAB
        uses: matlab-actions/run-command@v2
        with:
          command: matlab -batch "run('lab2.m')"
